"""
Django settings for fypext project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rqb79utolwkqe!$wjd*x5@$#_ys)cr7v-$@@!z(9w1yqc@p$ra'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_neomodel', 
    'fcm_django',
    # 'codearea.apps.CodeareaConfig'
    'codearea'
    
]


#  for firebase
FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "[AAAAuQxSVZA:APA91bEeqAnBCoosLSvW4fRHVnOVH861jqMELsTLMcGWMOQZjgtH2NceNQOKqM0AEKhwxaP8ndIFdQSqZNZp-jPTnoIpsVTXy4_NYP5z9Ljwm9Jzp2i3PxW35as0fVDMK6c60ShxfQRr]"
}

FCM_SERVER_KEY= "[AAAAuQxSVZA:APA91bEeqAnBCoosLSvW4fRHVnOVH861jqMELsTLMcGWMOQZjgtH2NceNQOKqM0AEKhwxaP8ndIFdQSqZNZp-jPTnoIpsVTXy4_NYP5z9Ljwm9Jzp2i3PxW35as0fVDMK6c60ShxfQRr]"









MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fypext.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fypext.wsgi.application'

#from neomodel import config
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# fariya code
NEOMODEL_NEO4J_BOLT_URL = os.environ.get('NEO4J_BOLT_URL','bolt://neo4j:nabeel@localhost:7687')
NEOMODEL_SIGNALS = True
NEOMODEL_FORCE_TIMEZONE = False
NEOMODEL_ENCRYPTED_CONNECTION = False
NEOMODEL_MAX_POOL_SIZE = 50


#net
# NEOMODEL_NEO4J_BOLT_URL = os.environ.get('NEO4J_BOLT_URL','bolt://neo4j:nabeel@localhost:7687')
# NEOMODEL_SIGNALS = True
# NEOMODEL_FORCE_TIMEZONE = False
# NEOMODEL_ENCRYPTED_CONNECTION = False
# NEOMODEL_MAX_POOL_SIZE = 50


# config.NEO4J_BOLT_URL = os.environ.get('NEO4J_BOLT_URL','bolt://neo4j:nabeel@localhost:7687')
# #config.DATABASE_URL = 'bolt://neo4j:nabeel@localhost:7687'
# config.SIGNALS = True
# config.FORCE_TIMEZONE = False
# config.ENCRYPTED_CONNECTION = False
# config.MAX_POOL_SIZE = 50







# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }








# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CORS_ORIGIN_ALLOW_ALL = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
