from codearea.views.persons import *
from codearea.views.User import *
from codearea.views.BusDriver import *
from codearea.views.SubBus import *
from codearea.views.Admin import *
from codearea.views.History import *
from codearea.views.Feedback import *
from codearea.views.Assignbus import *
from codearea.views.RouteManager import *
